dist: trusty
sudo: required
services:
- docker

before_install:
  - sudo apt-get update -qq

install:
  - sudo pip install ansible docker-py

env:
  matrix:
    - EMULATION_TYPE=dnet
    - EMULATION_TYPE=swarmkit

script: ./run-integration-test.sh
