---
- hosts:
    - kv_host
  roles:
    - { role: kvstore,
        tags: kvstore,
        when: libnetwork_install_type == "dnet" }

- hosts:
    - emulation-hosts
  roles:
    - { role: dnet,
        tags: dnet,
        when: libnetwork_install_type == "dnet" }

- hosts:
    - emulation-hosts
  roles:
    - { role: swarmkit,
        tags: swarmkit,
        when: libnetwork_install_type == "swarmkit" }
