---
- name: start dnet agents
  docker_container:
    name: "dnet-{{ item }}"
    image: "{{ dnet_image_full }}"
    pull: "{{ image_pull_policy }}"
    privileged: yes
    detach: True
    state: started
    published_ports:
        - "2385"
        - "7496"
    volumes:
        - "{{ node_config_directory }}/dnet-{{ item }}:/etc/dnet/:ro"
    command: "dnet -d -D -c /etc/dnet/dnet-libnetwork.toml"
  with_sequence: start=1 end={{ number_dnet_agents }}
  when:
    - inventory_hostname in groups['emulation-hosts']
