---
- name: start dnet agents
  docker:
    name: "dnet-{{ item }}"
    image: "{{ dnet_image_full }}"
    pull: "{{ image_pull_policy }}"
    privileged: yes
    detach: True
    state: started
    publish_all_ports: yes
    volumes:
        - "{{ node_config_directory }}/dnet-{{ item }}:/etc/dnet/:ro"
    command: "dnet -d -D -c /etc/dnet/dnet-libnetwork.toml"
  with_sequence: start=1 end={{ number_dnet_agents }}
  when:
    - inventory_hostname in groups['emulation-hosts']
