---
- name: start consul container
  docker_container:
    name: "consul"
    image: "{{ consul_image_full }}"
    pull: "{{ image_pull_policy }}"
    privileged: no
    ports:
        - "8500:8500"
        - "8300:8300/udp"
        - "8301:8301/udp"
        - "8302:8302/udp"
        - "8300:8300/tcp"
        - "8301:8301/tcp"
        - "8302:8302/tcp"
    detach: True
    state: started
